services:
  - type: web
    name: goku-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PORT
        value: 8080
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Set this in Render dashboard
      - key: GOOGLE_API_KEY
        sync: false  # Set this in Render dashboard
