services:
  - type: web
    name: goku-bot-health
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python health_check.py
    envVars:
      - key: PORT
        value: 8080
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase:
          name: telegram-bot-token
          property: connectionString
      - key: GOOGLE_API_KEY
        fromDatabase:
          name: google-api-key
          property: connectionString

  - type: worker
    name: goku-bot-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase:
          name: telegram-bot-token
          property: connectionString
      - key: GOOGLE_API_KEY
        fromDatabase:
          name: google-api-key
          property: connectionString
