services:
  - type: web
    name: goku-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_server.py
    envVars:
      - key: PORT
        value: 8080

  - type: worker
    name: goku-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false