name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test bot startup
      run: |
        python -c "import bot; print('Bot imports successfully')"
        python -c "import start; print('Start script imports successfully')"
        
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment triggered for commit ${{ github.sha }}"
        echo "Render will automatically deploy from GitHub"
